---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - synapse.io
  resources:
  - setups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synapse.io
  resources:
  - setups/finalizers
  verbs:
  - update
- apiGroups:
  - synapse.io
  resources:
  - setups/status
  verbs:
  - get
  - patch
  - update
