# permissions for end users to edit testinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: synapse-operator
    app.kubernetes.io/managed-by: kustomize
  name: testinstance-editor-role
rules:
- apiGroups:
  - synapse.io
  resources:
  - testinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synapse.io
  resources:
  - testinstances/status
  verbs:
  - get
