name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'control-plane/synapse-operator/**'
      - '!control-plane/synapse-operator/.github/**'
      - '!control-plane/synapse-operator/README.md'
      - '!control-plane/synapse-operator/helm/**'
  pull_request:
    paths:
      - 'control-plane/synapse-operator/**'
      - '!control-plane/synapse-operator/.github/**'
      - '!control-plane/synapse-operator/README.md'
      - '!control-plane/synapse-operator/helm/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mdaops/synapse

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=sha,prefix=,enable={{is_default_branch}}
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      run: |
        cd control-plane/synapse-operator
        make docker-build docker-push IMG='${{ fromJSON(steps.meta.outputs.json).tags[0] }}'